### ISSUE TITLE
[WinError 5] Access is denied

### ISSUE THREAD

**Issue by Roy-Oliver** [razumeiko/py-android-viewer#4]
I am using windows 7 64 bit. I already set the adb/scrcpy path in viewer.py after an error came up. Now, it shows the following error. I tried to open using admin, but still the same.

2020-05-22 19:01:55.013 INFO:	Upload JAR...
Traceback (most recent call last):
  File "E:/Pycharm_Projects/make_them_jump/test.py", line 3, in <module>
    a = viewer.AndroidViewer()
  File "E:\Pycharm_Projects\make_them_jump\viewer\viewer.py", line 43, in __init__
    assert self.deploy_server(max_width, bitrate, max_fps)
  File "E:\Pycharm_Projects\make_them_jump\viewer\viewer.py", line 96, in deploy_server
    adb_push = subprocess.Popen([self.adb_path, 'push', server_file_path, '/data/local/tmp/'],
  File "C:\Users\Oliver\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Oliver\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

**Comment by razumeiko** [comment]
Hi. I don't have windows machine to check it but i'd check two things:
1) Run console as admin and try to run your script
2) Check self.adb_path, is it set correctly? Try to  create empty python file with this line and  try to run adb, play with path or args.

**Comment by Roy-Oliver** [comment]
@razumeiko It's working now. I set adb_path to the adb.exe file, not the directory which contains adb.exe.

Thank you!
